// Converts the bundled example dataset (data/icgi.csv) into a typed TypeScript module.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const dataDir = path.join(here, "..", "data");
const csvPath = fs.existsSync(path.join(dataDir, "icgi.csv"))
  ? path.join(dataDir, "icgi.csv")
  : path.join(dataDir, "effICGI.csv");
const outPath = path.join(here, "..", "src", "data.generated.ts");

const raw = fs.readFileSync(csvPath, "utf8").trim().split(/\r?\n/);
const header = raw[0].split(",").map((h) => h.replace(/"/g, "").trim());
const doseToNumeric = { Placebo: 0, "600 mg": 600, "1200 mg": 1200, "1800 mg": 1800, "2400 mg": 2400 };

const numOrNull = (v) => {
  const n = Number(v);
  return v !== undefined && v !== "" && Number.isFinite(n) ? n : null;
};

const records = raw.slice(1).map((line, i) => {
  const cells = line.split(",").map((c) => c.replace(/"/g, ""));
  const row = {};
  header.forEach((h, j) => (row[h] = cells[j]));
  return {
    id: numOrNull(row.ID) ?? i,
    study: String(row.STUDY ?? ""),
    dose: row.DOSE,
    doseNumeric: doseToNumeric[row.DOSE] ?? (Number(row.GBDS) || 0),
    sex: numOrNull(row.SEX),
    age: numOrNull(row.AGE),
    wt: numOrNull(row.WT),
    race: numOrNull(row.RACE),
    crcl: numOrNull(row.CRCL),
    gbds: numOrNull(row.GBDS),
    auc: Number(row.AUC),
    cmax: Number(row.CMAX),
    icgi: Number(row.ICGI),
    icgi7: numOrNull(row.ICGI7),
    icgi2: Number(row.ICGI2),
    icgi3: Number(row.ICGI3),
    brls: numOrNull(row.BRLS),
    prls: numOrNull(row.PRLS)
  };
});

const srcName = path.basename(csvPath);
const banner = `// AUTO-GENERATED by scripts/build-data.mjs from data/${srcName}. Do not edit by hand.\n`;
const body = `export interface ExposureResponseRecord {
  id: number;
  study: string;
  dose: string;
  doseNumeric: number;
  sex: number | null;
  age: number | null;
  wt: number | null;
  race: number | null;
  crcl: number | null;
  gbds: number | null;
  auc: number;
  cmax: number;
  icgi: number;
  icgi7: number | null;
  icgi2: number;
  icgi3: number;
  brls: number | null;
  prls: number | null;
}

export const RECORDS: ExposureResponseRecord[] = ${JSON.stringify(records)};\n`;

fs.writeFileSync(outPath, banner + body);
console.log(`Wrote ${records.length} records from ${srcName} to ${path.relative(process.cwd(), outPath)}`);
