// Converts the bundled example dataset (data/effICGI.csv) into a typed
// TypeScript module so it can be embedded directly in the self-contained
// demo bundle without a runtime fetch/CSV parse step.
//
// Source: example exposure-response dataset (AUC/CMAX exposure metrics,
// ICGI clinical response endpoints, dose group) from the ggquickeda
// package's exposure-response vignette, provided by the ER Explorer author.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const csvPath = path.join(here, "..", "data", "effICGI.csv");
const outPath = path.join(here, "..", "src", "data.generated.ts");

const raw = fs.readFileSync(csvPath, "utf8").trim().split(/\r?\n/);
const header = raw[0].split(",").map((h) => h.replace(/"/g, "").trim());
const doseToNumeric = { Placebo: 0, "600 mg": 600, "1200 mg": 1200, "1800 mg": 1800, "2400 mg": 2400 };

// A handful of BRLS/PRLS values are missing in the source CSV (a patient with no post-baseline
// rating at that visit) - represented as `null` rather than coerced to 0, so a missing score is
// never silently treated as an observed one downstream.
const numOrNull = (v) => {
  const n = Number(v);
  return v !== undefined && v !== "" && Number.isFinite(n) ? n : null;
};

const records = raw.slice(1).map((line, i) => {
  const cells = line.split(",").map((c) => c.replace(/"/g, ""));
  const row = {};
  header.forEach((h, j) => (row[h] = cells[j]));
  return {
    id: i,
    study: row.STUDY,
    dose: row.DOSE,
    doseNumeric: doseToNumeric[row.DOSE] ?? (Number(row.GBDS) || 0),
    auc: Number(row.AUC),
    cmax: Number(row.CMAX),
    icgi: Number(row.ICGI),
    icgi2: Number(row.ICGI2),
    icgi3: Number(row.ICGI3),
    // BRLS/PRLS: continuous rating-scale endpoints (as opposed to ICGI/ICGI2/ICGI3's binary
    // responder/non-responder endpoints) - fit with the linear (OLS) model instead of logistic.
    // `null` where the source CSV has no value for that patient/visit.
    brls: numOrNull(row.BRLS),
    prls: numOrNull(row.PRLS)
  };
});

const banner = `// AUTO-GENERATED by scripts/build-data.mjs from data/effICGI.csv. Do not edit by hand.\n`;
const body = `export interface ExposureResponseRecord {\n  id: number;\n  study: string;\n  dose: string;\n  doseNumeric: number;\n  auc: number;\n  cmax: number;\n  icgi: number;\n  icgi2: number;\n  icgi3: number;\n  brls: number | null;\n  prls: number | null;\n}\n\nexport const RECORDS: ExposureResponseRecord[] = ${JSON.stringify(records)};\n`;

fs.writeFileSync(outPath, banner + body);
console.log(`Wrote ${records.length} records to ${path.relative(process.cwd(), outPath)}`);
